config/routes.rb
Rails.application.routes.draw do
  
  
  
  
  devise_for :users
  get 'homes/top'
  get "home/about" => "homes#about"
  

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  post 'follow/:id' => 'relationships#follow',as:'follow'
  post 'unfollow/:id' => 'relationships#unfollow',as:'anfollow'
  
  get "search" => "searches#search"
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

end

app/models/book.rb
class Book < ApplicationRecord
  
  has_one_attached :image
  belongs_to :user
   has_many :favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def new
    @book = book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end
  
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:success] = "successfully delete book!"
    redirect_to books_path
  end
  
  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
  
    def ensure_correct_user
     @book = Book.find(params[:id])
     return if @book.user_id == current_user.id
     redirect_to books_path
    end 
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<table>
  <% @book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= image_tag book_comment_user.get_profile_image(50,50) %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), class: 'btn-sm btn-danger', method: :delete %></td>
    	<% end %>
    </tr>
  <% end %>
</table>
<%= form_with model:[@book,@book_comment], local: true do |f| %>
  <%= f.text_area :comment, size:"90x5" %><br>
  <%= f.submit '送信'%>
<% end %>

app/views/books/_form.html.erb
<% if book.errors.any? %>
 <%= book.errors.count %>errors prohibited this obj from being saved:
 <% book.errors.full_messages.each do |message| %>
 <%= message %>
 <% end %>
<% end %>

<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
          <% end %>
        </td>
        <td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td id="favorite_btn_<%= book.id %>"><%= render "favorites/favorite", book: book %></td>
        <td>コメント数: <%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to "Show", @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(100, 100) %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td id= "favorite_btn_<%= @book.id %>"><%= render "favorites/favorite", book: @book %></td>
          <td>コメント数: <%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <%= render 'books/comment', book: @book,book_comment: @book_comment%>
    </div>
  </div>
</div>